version: "3.9"

services:
  web:
    build: .
    env_file: .env
    command: npm run dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onboardingdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres-data:
  node_modules:
